assetic:
    bundles:
        - CampaignChainOperationFacebookBundle
    assets:
        campaignchain_operation_facebook_css:
            inputs:
                - '@CampaignChainOperationFacebookBundle/Resources/public/css/base.css'
twig:
    form_themes:
        - 'CampaignChainOperationFacebookBundle:Form:fields.html.twig'

liip_imagine:
    filter_sets:
        campaignchain_facebook_photo:
            filters:
                auto_rotate: ~
                downscale:
                    max: [1200, 900]