# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

services:
    campaignchain.operation.facebook.job.publish_status:
        class: CampaignChain\Operation\FacebookBundle\Job\PublishStatus
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.operation.facebook.status:
        class: CampaignChain\Operation\FacebookBundle\EntityService\Status
        arguments: [ @doctrine.orm.entity_manager ]