# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.operation.facebook.publish_status:
        bundle_name: "campaignchain/operation-facebook"
        module_identifier: "campaignchain-facebook-publish-status"
        form_type: "CampaignChain\\Operation\\FacebookBundle\\Form\\Type\\PublishStatusOperationType"

services:
    campaignchain.job.operation.facebook.publish_status:
        class: CampaignChain\Operation\FacebookBundle\Job\PublishStatus
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.job.report.facebook.publish_status:
        class: CampaignChain\Operation\FacebookBundle\Job\ReportPublishStatus
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.operation.facebook.status:
        class: CampaignChain\Operation\FacebookBundle\EntityService\Status
        arguments: [ @doctrine.orm.entity_manager ]